Dynamics Crm Connector: DynamicsCrm Class Reference
DynamicsCrm Class Reference
Public Member Functions
__construct ($serv_adress, $user, $password)
getServAdress ()
setServAdress ($serv_adress)
getUser ()
setUser ($user)
getPassword ()
setPassword ($password)
Retrieve ($Table, $Id, $Columns)
RetrieveMultiple ($Table, $Where, $Columns=false, $Join=false, $Order=false)
Delete ($Table, $Id)
Update ($Table, $Params, $Id)
Create ($Table, $Params)
SetState ($Id, $Table, $StateCode, $StatusCode)
GetAllEntities ()
Workflow ($EntityId, $WorkflowId)
Associate ()
GetCurrentUserInfo ()
Data Fields
$serv_adress
$user
$password
Private Member Functions
ExecuteBody ($Request)
call ($operation, $soapBody)
FormatFetchEntity ($EntityName)
FormatFetchAttribute ($Columns)
FormatAttributes ($Params)
FormatAttribute ($Param)
TestParameters ($Param, $Fields)
TestParameter ($Param, $field)
TestAgreggate ($Param)
GetErrorObject ($message)
FormatColumn ($Columns)
FormatFetchOrder ($Orders)
FormatFetchFilter ($Filters)
FormatFetchJoin ($Joins)
FormatCondition ($Filter)
ParseRetrieveMultiple ($xml, $Return)
ParseDatas ($Datas, $Return)
ParseResultLine ($Data)
ParseKeyPair ($data)
ParseRetrieve ($xml, $Return)
GenerateSoapHeader ($operation)
array_key_exists_r ($needle, $haystack)
Private Attributes
$StateCheck
$Aggregate = array ('avg','max','min','sum','count','countcolumn','countdistinct')
$Operator
Detailed Description
Definition at line 67 of file DynamicsCrm.php.
Constructor & Destructor Documentation
__construct ($serv_adress, $user, $password)
Constructor
Parameters
string $serv_adress Url to service
string $user Dynamics CRM connection's User
(LDAP) Domain/user
Parameters
string $password Dynamics CRM connection's password
Definition at line 128 of file DynamicsCrm.php.
References setPassword(), setServAdress(), and setUser().
{
         $this->setServAdress ( $serv_adress );
         $this->setUser ( $user );
         $this->setPassword ( $password );
     }
Member Function Documentation
array_key_exists_r ($needle, $haystack) private
Recursive array_key_exist
Parameters
$needle what you want to find
$haystack where you want to find it
Returns
boolean
Definition at line 1346 of file DynamicsCrm.php.
Referenced by RetrieveMultiple().
{
         $result = array_key_exists ( $needle, $haystack );
         if ($result)
             return $result;
         foreach ( $haystack as $v ) {
             if (is_array ( $v ) || is_object ( $v ))
                 $result = $this->array_key_exists_r ( $needle, $v );
             if ($result)
                 return $result;
         }
         return $result;
     }
Associate ()
Todo:
Returns
result
Definition at line 525 of file DynamicsCrm.php.
References call().
{
         $SoapEnvelope = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                             <soap:Body>
             <Associate xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Services">
             <subType>
             </subType>
             <objectType>
             10069</objectType>
             <parentObjectType>10095</parentObjectType>
             <objectId>568B31F9-8AEE-E211-8830-005056B74E4F</objectId>
             <parentId>A5DF8846-3BF0-E211-8830-005056B74E4F</parentId>
             <associationName>classification_occupation</associationName>
             </Associate></soap:Body>
         </soap:Envelope>';
         return $this->call ( 'Associate', $SoapEnvelope );
     }
call ($operation, $soapBody) private
Format Entity Header
Parameters
string $operation Name of the action to be done
string $soapBody Soap body request according to the Action
Returns
result parsed and in an CrmResponse Object according to action
Definition at line 585 of file DynamicsCrm.php.
References GenerateSoapHeader(), ParseRetrieve(), and ParseRetrieveMultiple().
Referenced by Associate(), Create(), Delete(), ExecuteBody(), Retrieve(), RetrieveMultiple(), and Update().
{
         $headers = $this->GenerateSoapHeader ( $operation );
         $ch = curl_init ();
         curl_setopt ( $ch, CURLOPT_URL, $this->serv_adress );
         curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, true );
         curl_setopt ( $ch, CURLOPT_HTTPHEADER, $headers );
         curl_setopt ( $ch, CURLOPT_POST, true );
         curl_setopt ( $ch, CURLOPT_POSTFIELDS, $soapBody );
         curl_setopt ( $ch, CURLOPT_HTTPAUTH, CURLAUTH_NTLM );
         curl_setopt ( $ch, CURLOPT_USERPWD, $this->user . ':' . $this->password );
         $response = curl_exec ( $ch );
         $Return = new CrmResponse ();
         if ($response === false) {
             $Return->Error = True;
             $Return->ErrorCode = 0;
             $Return->ErrorMessage = curl_error ( $ch );
             $Return->Result = False;
         } else {
             $response = str_replace ( '<a:', '<', $response );
             $response = str_replace ( '<b:', '<', $response );
             $response = str_replace ( '<c:', '<', $response );
             $response = str_replace ( '<s:', '<', $response );
             $response = str_replace ( '</a:', '</', $response );
             $response = str_replace ( '</b:', '</', $response );
             $response = str_replace ( '</c:', '</', $response );
             $response = str_replace ( '</s:', '</', $response );
             $xml = simplexml_load_string ( $response );
             if (isset ( $xml->Body->Fault )) {
                 $Return->Error = True;
                 $Return->ErrorCode = ( string ) $xml->Body->Fault->faultcode;
                 $Return->ErrorMessage = ( string ) $xml->Body->Fault->faultstring;
                 $Return->Result = False;
             } else {
                 switch ($operation) {
                     case 'RetrieveMultiple' :
                         $Return = $this->ParseRetrieveMultiple ( $xml, $Return );
                         Break;
                     case 'Retrieve' :
                         $Return = $this->ParseRetrieve ( $xml, $Return );
                         Break;
                     case 'Create' :
                         $Return->NbResult = 1;
                         $Return->Result = ( string ) $xml->Body->CreateResponse->CreateResult;
                         Break;
                     case 'Update' :
                         if (isset ( $xml->Body->UpdateResponse )) {
                             $Return->NbResult = 1;
                             $Return->Result = true;
                         } else {
                             $Return->Error = True;
                             $Return->ErrorCode = "Unknown Error";
                             $Return->ErrorMessage = "Unknown Error";
                         }
                         Break;
                     case 'Execute' :
                         $Return->NbResult = 1;
                         $Return->Result = $xml;
                         break;
                     case 'Associate' :
                         die ( print_r ( $xml ) );
                         break;
                     case 'Delete' :
                         if (isset ( $xml->Body->DeleteResponse )) {
                             $Return->NbResult = 1;
                             $Return->Result = true;
                         } else {
                             $Return->Error = True;
                             $Return->ErrorCode = "Unknown Error";
                             $Return->ErrorMessage = "Unknown Error";
                         }
                         Break;
                 }
             }
         }
         return $Return;
     }
Create ($Table, $Params)
Create a new row
Parameters
string $Table
the table where you want to create a new row
Parameters
array $Params
array(
1=>array(
'field'=>'fieldname',
'type'=>'Field type',
'value'=>'value'
) ,
2=>array(
'field'=>'fieldname',
'type'=>'EntityReference',
'id'=>'guidforentity',
'name'=>'entityname(table)'
) ,
*)
Returns
objet CrmResponse.
Bool $Error,
String $ErrorCode,
String $ErrorMessage,
$Result => Guid or false depending if query worked or not,
Definition at line 406 of file DynamicsCrm.php.
References call(), FormatAttributes(), and GetErrorObject().
{
         try {
             $Param = $this->FormatAttributes ( $Params );
         } catch ( Exception $e ) {
             return $this->GetErrorObject ( $e->getMessage () );
         }
         $SoapEnvelope = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                             <soap:Body>
                 <Create xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Services">
             <entity xmlns:b="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                     <b:Attributes xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
                        ' . $Param . '
                     </b:Attributes>
                         <b:EntityState i:nil="true"/>
                         <b:FormattedValues />
                         <b:Id>00000000-0000-0000-0000-000000000000</b:Id>
                         <b:LogicalName>' . $Table . '</b:LogicalName>
                         <b:RelatedEntities />
                 </entity></Create></soap:Body>
         </soap:Envelope>';
         return $this->call ( 'Create', $SoapEnvelope );
     }
Delete ($Table, $Id)
Delete a row
Parameters
string $Table
the table where you want to delete a row
Parameters
string $Id mostly a GUID from the id column (key) ...
Returns
obj CrmResponse.
Bool $Error,
String $ErrorCode,
String $ErrorMessage,
$Result => Guid or false depending if query worked or not,
Definition at line 310 of file DynamicsCrm.php.
References call().
{
         // build soap Enveloppe
         $SoapEnvelope = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://schemas.microsoft.com/xrm/2011/Contracts/Services">
                             <soap:Header/>
                                 <soap:Body>
                                     <ser:Delete>
                                         <ser:entityName>' . $Table . '</ser:entityName>
                                         <ser:id>' . $Id . '</ser:id>
                                     </ser:Delete>
                                 </soap:Body>
                         </soap:Envelope>';
         // call
         Return $this->call ( "Delete", $SoapEnvelope );
     }
ExecuteBody ($Request) private
Format Entity Header
Parameters
string $Request Request Body for Execute
Returns
result parsed and in an CrmResponse Object according to action
Definition at line 565 of file DynamicsCrm.php.
References call().
Referenced by GetAllEntities(), GetCurrentUserInfo(), SetState(), and Workflow().
{
         $SoapEnvelope = '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
                              <s:Body>
                                  <Execute xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Services" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                                     ' . $Request . '
                                 </Execute>
                             </s:Body>
                         </s:Envelope>';
         return $this->call ( 'Execute', $SoapEnvelope );
     }
FormatAttribute ($Param) private
Format Attributes for insert updates and execute
Parameters
array $Param Attribute parameter
array(
'field'=>'fieldname',
'type'=>'Field type',
'value'=>'value'
)
array(
'field'=>'fieldname',
'type'=>'EntityReference',
'id'=>'guidforentity',
'name'=>'entityname(table)'
)
Returns
correct Attribute XML for insert/update/execute cases
Definition at line 818 of file DynamicsCrm.php.
References TestParameter(), and TestParameters().
Referenced by FormatAttributes().
{
         $TxtAttribute = "";
         $this->TestParameters ( $Param, array('field','type') );
         if (isset ( $Param ['field'] ) && isset ( $Param ['type'] )) {
             $TxtAttribute .= '<b:KeyValuePairOfstringanyType>
                             <c:key>' . $Param ['field'] . '</c:key>';
             switch ($Param ['type']) {
                 case 'OptionSetValue' :
                 case 'optionsetvalue' :
                 case 'option' :
                 case 'Option' :
                     $this->TestParameter ( $Param, 'value' );
                     $TxtAttribute .= '<c:value i:type="b:OptionSetValue"><b:value>' . $Param ['value'] . '</b:value></c:value>';
                     break;
                 case 'Money' :
                 case 'money' :
                     $this->TestParameter ( $Param, 'value' );
                     $TxtAttribute .= '<c:value i:type="b:Money"><b:value>' . $Param ['value'] . '</b:value></c:value>';
                     break;
                 case 'Boolean' :
                 case 'boolean' :
                 case 'bool' :
                 case 'Bool' :
                     $this->TestParameter ( $Param, 'value' );
                     $TxtAttribute .= '<c:value i:type="d:boolean" xmlns:d="http://www.w3.org/2001/XMLSchema">' . $Param ['value'] . '</c:value>';
                     break;
                 case 'Integer' :
                 case 'integer' :
                 case 'Int' :
                 case 'int' :
                     $this->TestParameter ( $Param, 'value' );
                     $TxtAttribute .= '<c:value i:type="d:int" xmlns:d="http://www.w3.org/2001/XMLSchema">' . $Param ['value'] . '</c:value>';
                     break;
                 case 'DateTime' :
                 case 'datetime' :
                     $this->TestParameter ( $Param, 'value' );
                     $TxtAttribute .= '<c:value i:type="d:dateTime" xmlns:d="http://www.w3.org/2001/XMLSchema">' . $Param ['value'] . '</c:value>';
                     break;
                 case 'String' :
                 case 'string' :
                 default :
                     $this->TestParameter ( $Param, 'value' );
                     $TxtAttribute .= '<c:value i:type="d:string" xmlns:d="http://www.w3.org/2001/XMLSchema">' . $Param ['value'] . '</c:value>';
                     break;
                 case 'EntityReference' :
                 case 'entityreference' :
                 case 'Entity' :
                 case 'entity' :
                     $this->TestParameter ( $Param, 'id','name' );
                     $TxtAttribute .= '<c:value i:type="b:EntityReference">
                                                 <b:Id>' . $Param ["id"] . '</b:Id>
                                                 <b:LogicalName>' . $Param ["name"] . '</b:LogicalName>
                                                 <b:Name i:nil="true" />
                                                 </c:value>';
                     break;
                 case 'ActivityParty' :
                 case 'Activity' :
                 case 'activityparty' :
                 case 'activity' :
                 case 'ArrayOfEntity' :
                 case 'arrayofentity' :
                 case 'Array' :
                 case 'array' :
                     $TxtAttribute .= '<c:value i:type="b:ArrayOfEntity">';
                     $this->TestParameter ( $Param, 'value' );
                     foreach ( $Param ['value'] as $entity ) {
                         $TxtAttribute .= ' <b:Entity>
                                     <b:Attributes>';
                         $TxtAttribute .= $this->FormatAttribute ( $entity );
                         $TxtAttribute .= '</b:Attributes><b:Entitystate i:nil="true" />
                             <b:FormattedValues />
                                 <b:Id>00000000-0000-0000-0000-000000000000</b:Id>
                             <b:LogicalName>activityparty</b:LogicalName>
                             <b:RelatedEntities />
                             </b:Entity>';
                     }
                     $TxtAttribute .= '
                                 </c:value>';
                     break;
             }
             $TxtAttribute .= '</b:KeyValuePairOfstringanyType>';
         }
         return $TxtAttribute;
     }
FormatAttributes ($Params) private
Format Attributes for insert,updates and execute
Parameters
array $Params Attributes parameter
array(
1=>array(
'field'=>'fieldname',
'type'=>'Field type',
'value'=>'value'
) ,
2=>array(
'field'=>'fieldname',
'type'=>'EntityReference',
'id'=>'guidforentity',
'name'=>'entityname(table)'
) 3=>array(
'field'=>'fieldname',
'type'=>'ActivityParty',
'value'=>array(
"entity1"=>array(
1=>array(
'field'=>'fieldname',
'type'=>'Field type',
'value'=>'value'
) ,
2=>array(
'field'=>'fieldname',
'type'=>'EntityReference',
'id'=>'guidforentity',
'name'=>'entityname(table)'
)
)
)
,
*)
Returns
correct Attributes XML for insert/update/execute cases
Definition at line 785 of file DynamicsCrm.php.
References FormatAttribute().
Referenced by Create(), and Update().
{
         $TxtAttribute = "";
         if (is_array ( $Params )) {
             foreach ( $Params as $Param ) {
                 $TxtAttribute .= $this->FormatAttribute ( $Param );
             }
         }
         return $TxtAttribute;
     }
FormatColumn ($Columns) private
Format Columns for REtrieveMultiple
Parameters
array $Columns array with colnames or false for all col
array(
'colname1',
'colname2'...
)
notice it will always return GUID Except with agregate function
Returns
correct Columns XML for REtrieveMultiple
Definition at line 961 of file DynamicsCrm.php.
Referenced by Retrieve().
{
         if ($Columns !== false && ! is_array ( $Columns )) {
             throw new \InvalidArgumentException ( sprintf ( "Column Parameter  invalid : $Columns" ) );
             }
         $AllCol = ($Columns == false) ? "true" : "false";
         $TxtColumn = '<ser:columnSet><con:AllColumns>' . $AllCol . '</con:AllColumns><con:Columns>';
         if ($Columns != false) {
             foreach ( $Columns as $Column ) {
                 $TxtColumn .= '<arr:string>' . $Column . '</arr:string>';
             }
         }
         $TxtColumn .= '</con:Columns></ser:columnSet>';
         return $TxtColumn;
     }
FormatCondition ($Filter) private
Format condition Depending on Operator
Parameters
array $Filter,<p> *array(
*'Column' => (String) $ColumnName
*'Op' => Operator link to all operator
*'Value' => $Value (if necessary depending on operator, data or could be an array)
*'Value2' => $Value2 (if necessary mostly in between case)
*)
Returns
correct XML for request this condition
Definition at line 1137 of file DynamicsCrm.php.
References TestParameters().
Referenced by FormatFetchFilter().
{
         /*
          * The operators wich dont need a value
          * so no need for value here
          */
         if (in_array ( $Filter ['Op'], $this->Operator ['0'] )) {
             $Condition = "&lt;condition attribute='" . $Filter ['Column'] . "' operator='" . $Filter ['Op'] . "' /&gt;";
             /*
              * The basic operators
              * Value to be set, nothing much
              */
         } else if (in_array ( $Filter ['Op'], $this->Operator ['1'] )) {
             $this->TestParameters ( $Filter, array (
                     'Column',
                     'Value'
             ) );
             $Condition = "&lt;condition attribute='" . $Filter ['Column'] . "' operator='" . $Filter ['Op'] . "' value='" . $Filter ['Value'] . "'  /&gt;";
             /*
              * The in operators
              * Value is now an array with data to be tested array('1','2',...)
              */
         } else if (in_array ( $Filter ['Op'], $this->Operator ['2'] )) {
             $this->TestParameters ( $Filter, array (
                     'Column',
                     'Value'
             ) );
             $Condition = "&lt;condition attribute='" . $Filter ['Column'] . "' operator='" . $Filter ['Op'] . "' &gt;";
             if (! is_array ( $Filter ['Value'] )) {
                 $TxtFilter = print_r ( $Filter, true );
                 throw new \InvalidArgumentException ( sprintf ( "Filter Incorrect [Value] for this kind of operator should be an array  : $TxtFilter" ) );
             }
             foreach ( $Filter ['Value'] as $Value ) {
                 $Condition .= '&lt;value&gt;' . $Value . '&lt;/value&gt;';
             }
             $Condition .= '&lt;/condition &gt;';
             /*
              * The 2 values operator
              * Value and Value2 in array
              */
         } else if (in_array ( $Filter ['Op'], $this->Operator ['3'] )) {
             $this->TestParameters ( $Filter, array (
                     'Column',
                     'Value','Value2'
             ) );
             $Condition = "&lt;condition attribute='" . $Filter ['Column'] . "' operator='" . $Filter ['Op'] . "' &gt;";
             $Condition .= '&lt;value&gt;' . $Filter ['Value'] . '&lt;/value&gt; &lt;value&gt;' . $Filter[
                     'Value2'
             ] . '&lt;/value&gt;';
             $Condition .= '&lt;/condition &gt;';
         } else {
             $ListOperator = print_r ( $this->Operator, true );
             throw new \InvalidArgumentException ( sprintf ( "Condition '" . $Filter ['Op'] . "' Invalid should be in : $ListOperator" ) );
         }
         return $Condition;
     }
FormatFetchAttribute ($Columns) private
Format Fetch Attributes
(Column being resolved by RetrieveMultiple)
Parameters
array $Columns
simple request
array(
'Colname1',
'Colname2'...
)
*aggregate request
array(
'1'=>array(
'name'=>'colname',
'alias'=> 'alias',(false,notset => will keep colname as alias)
'aggregate' =>'aggregate function name' ,if aggregate function needed else false or unset (avg , max, min, sum, count => SQL : (COUNT(*)) ,countcolumn => SQL : (COUNT(name)) ,countdistinct => SQL : (COUNT(DISTINCT name)))
),
'2'=> array(
'name'=>'colname',
'alias'=> 'alias',(false,notset => will keep colname as alias)
'groupby' =>true or year,quarter,month,week,day for date grouping
)
)
note that you cant mix simple column with agregates
Returns
correct XML for Columns
Definition at line 704 of file DynamicsCrm.php.
References TestAgreggate(), and TestParameter().
Referenced by FormatFetchJoin(), and RetrieveMultiple().
{
         $Attributes = "";
         if (is_array ( $Columns )) {
             foreach ( $Columns as $column ) {
                 if (is_array ( $column )) {
                     $this->TestParameter ( $column, 'name' );
                     // aggregate cases
                     if (isset ( $column ['name'] )) {
                         if (empty ( $column ['alias'] )) {
                             $column ['alias'] = $column ['name'];
                         }
                         // basic aggregate function avg , max, min, sum, count (COUNT(*)) ,countcolumn (COUNT(name)) ,countdistinct (COUNT(DISTINCT name))
                         if (! empty ( $column ['aggregate'] )) {
                             $this->TestAgreggate ( $column ['aggregate'] );
                             if ($column ['aggregate'] == 'countdistinct') {
                                 $Attributes .= "&lt;attribute name='" . $column ['name'] . "' alias='" . $column ['alias'] . "' aggregate='countcolumn' distinct='true' /&gt;";
                             } else {
                                 $Attributes .= "&lt;attribute name='" . $column ['name'] . "' alias='" . $column ['alias'] . "' aggregate='" . $column ['aggregate'] . "' /&gt;";
                             }
                             // so is that a groupby?
                         } else if (isset ( $column ['groupby'] )) {
                             $this->TestParameter ( $column, 'alias' );
                             if (isset ( $column ['alias'] )) {
                                 if ($column ['groupby'] !== true) {
                                     $Attributes .= "&lt;attribute name='" . $column ['name'] . "' alias='" . $column ['alias'] . "' dategrouping='" . $column ['groupby'] . "' groupby='true' /&gt;";
                                 } else {
                                     $Attributes .= "&lt;attribute name='" . $column ['name'] . "' alias='" . $column ['alias'] . "' groupby='true' /&gt;";
                                 }
                             }
                         }
                         // normal cases
                     }
                 } else
                     $Attributes .= "&lt;attribute name='" . $column . "' /&gt;";
             }
         }
         return $Attributes;
     }
FormatFetchEntity ($EntityName) private
Format Entity Header
Parameters
$EntityName String
Returns
correct XML for Entity header
Definition at line 672 of file DynamicsCrm.php.
Referenced by RetrieveMultiple().
{
         return " &lt;entity name='" . $EntityName . "'&gt;";
     }
FormatFetchFilter ($Filters) private
Format Filters for request will return a Filter is Type is set else will retun a condition
Parameters
array $Filter
basic and req where condition1 and condition2
array(
Condition1=>array
Condition2=>array
)
basic or req where condition1 or condition2
array(
'Type'=>'or'
Condition1=>array
Condition2=>array
)
multiple occurence and/or can be tricky
where ((condition1 and condition2) or ((condition5 and condition6)or condition4))
array (
Type=>'or'
1=>array(
'Type'=>'and'
Condition1=>array
Condition2=>array
)
2=>array(
'Type'=>'or'
Condition3=>array(
'Type'=>'and'
Condition5=>array
Condition6=>array
)
Condition4=>array
)
)
Check FormatCondition for more information about each operator
Returns
correct XML for thoose filters
Definition at line 1050 of file DynamicsCrm.php.
References FormatCondition().
{
         $TxtFilter = "";
         if (is_array ( $Filters )) {
             if (isset ( $Filters ['Type'] )) {
                 $TxtHead = "&lt;filter type='" . $Filters ['Type'] . "' &gt;";
             } else {
                 $TxtHead = '&lt;filter &gt;';
             }
             foreach ( $Filters as $Filter ) {
                 if (isset ( $Filter ['Type'] )) {
                     $TxtFilter .= $this->FormatFetchFilter ( $Filter );
                 } else {
                     if (isset ( $Filter ['Op'] )) {
                         $TxtFilter .= $this->FormatCondition ( $Filter );
                     }
                 }
             }
             if($TxtFilter!=""){
             $TxtFilter=$TxtHead.$TxtFilter.'&lt;/filter &gt;';
             return $TxtFilter;
             }else return "";
         } else  return "";
     }
FormatFetchJoin ($Joins) private
Format Join for RetriveMultiple
Parameters
array $Joins
array(
1=>array(
'name' => (String) tablename
'from' => join name On 'from'=to
'to' => join name On from='to'
'alias' =>not necessary can be false but aliases will be used when you try to get back ur data meaning $result->alias.data
'type' => Operator
'colums' => array see FormatColumn for detail
'where' => array see FormatFetchFilter for detail
'nested'=> (reproduce the same pattern and will nest a join false or unset if not required)
),
2=>array('name'=>...)
)
if only one join is required u can go directly with no nested array
    </p>
Returns
correct XML for request this condition
Definition at line 1100 of file DynamicsCrm.php.
References FormatFetchAttribute(), and TestParameters().
Referenced by RetrieveMultiple().
{
         // so we dont have to make a special statement for only 1 join
         $TxtJoin = "";
         if (isset ( $Joins ['name'] )) {
             $Joins = array (
                     '1' => $Joins
             );
         }
         foreach ( $Joins as $Join ) {
             $this->TestParameters($Join,array('name','from','to','type','columns','where'));
             $TxtJoin .= "&lt;link-entity name='" . $Join ['name'] . "' from='" . $Join ['from'] . "' to='" . $Join ['to'] . "' ";
             if (! empty ( $Join ['alias'] )){
                 $TxtJoin .= " alias='" . $Join ['alias'] . "' ";
             }
             $TxtJoin .= " link-type='" . $Join ['type'] . "' &gt;";
             $TxtJoin .= $this->FormatFetchAttribute ( $Join ['columns'] );
             if (! empty ( $Join ['nested'] ))
                 $TxtJoin .= FormatFetchJoin ( $Join );
             $TxtJoin .= $this->formatFetchFilter ( $Join ['where'] );
             $TxtJoin .= "&lt;/link-entity&gt;";
         }
         return $TxtJoin;
     }
FormatFetchOrder ($Orders) private
Format Order by for the request
Parameters
array $Order Clause order by
array(
1=>array(
'Column'=> 'ColumName',
'Order'=>'Asc'
),
2=>array(
'Column'=> 'ColumName2',
'Order'=>'Desc'
)..
)
Returns
correct XML for this Order by
Definition at line 993 of file DynamicsCrm.php.
References TestParameters().
Referenced by RetrieveMultiple().
{
         $TxtOrder = "";
         if (is_array ( $Orders )) {
             foreach ( $Orders as $Order ) {
                 $this->TestParameters ( $Order, array('Column','Order'));
                 if (isset ( $Order ['Column'] ) && isset ( $Order ['Order'] )) {
                     $TxtOrder .= "&lt;order attribute='" . $Order ['Column'] . "' descending='";
                     $TxtOrder .= ($Order ['Order'] == 'Asc') ? "false" : "true";
                     $TxtOrder .= "' /&gt;";
                 }
             }
         }
         return $TxtOrder;
     }
GenerateSoapHeader ($operation) private
Generate Header accordingly to the operation chosen
Parameters
string $operation Operation name (wdsl wise)
Returns
array formated Header
Definition at line 1324 of file DynamicsCrm.php.
Referenced by call().
{
         $soap_action = 'http://schemas.microsoft.com/xrm/2011/Contracts/Services/IOrganizationService/' . $operation;
         $headers = array (
                 'Method: POST',
                 'Connection: Keep-Alive',
                 'User-Agent: PHP-SOAP-CURL',
                 'Content-Type: text/xml; charset=utf-8',
                 'SOAPAction: "' . $soap_action . '"'
         );
         return $headers;
     }
GetAllEntities ()
Returns
result
Definition at line 476 of file DynamicsCrm.php.
References ExecuteBody().
{
         $Request = '<request i:type="a:RetrieveAllEntitiesRequest" xmlns:a="http://schemas.microsoft.com/xrm/2011/Contracts">
                    <a:Parameters xmlns:b="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
                      <a:KeyValuePairOfstringanyType>
                        <b:key>EntityFilters</b:key>
                        <b:value i:type="c:EntityFilters" xmlns:c="http://schemas.microsoft.com/xrm/2011/Metadata">Privileges</b:value>
                      </a:KeyValuePairOfstringanyType>
                      <a:KeyValuePairOfstringanyType>
                        <b:key>RetrieveAsIfPublished</b:key>
                        <b:value i:type="c:boolean" xmlns:c="http://www.w3.org/2001/XMLSchema">true</b:value>
                      </a:KeyValuePairOfstringanyType>
                    </a:Parameters>
                    <a:RequestId i:nil="true" />
                    <a:RequestName>RetrieveAllEntities</a:RequestName>
                  </request>
               ';
         $Return = $this->ExecuteBody ( $Request );
         return $Return;
     }
GetCurrentUserInfo ()
Returns
object
Definition at line 546 of file DynamicsCrm.php.
References ExecuteBody(), and ParseDatas().
{
         $Request = '<request i:type="b:WhoAmIRequest" xmlns:a="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:b="http://schemas.microsoft.com/crm/2011/Contracts">
                             <a:Parameters xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
                             <a:RequestId i:nil="true" />
                             <a:RequestName>WhoAmI</a:RequestName>
                           </request>';
         $Return = $this->ExecuteBody ( $Request );
         $Return = $this->ParseDatas ( $Return->Result->Body->ExecuteResponse->ExecuteResult->Results, $Return );
         return $Return;
     }
GetErrorObject ($message) private
Parameters
unknown $message
Returns
CrmResponse
Definition at line 941 of file DynamicsCrm.php.
Referenced by Create(), RetrieveMultiple(), SetState(), and Update().
{
         $Return = new CrmResponse ();
         $Return->Error = True;
         $Return->ErrorCode = 0;
         $Return->ErrorMessage = $message;
         $Return->Result = False;
         return $Return;
     }
getPassword ()
Returns
Dynamics CRM connection's password
Definition at line 175 of file DynamicsCrm.php.
References $password.
{
         return $this->password;
     }
getServAdress ()
Returns
Dynamics CRM connection's Url to service
Definition at line 138 of file DynamicsCrm.php.
References $serv_adress.
{
         return $this->serv_adress;
     }
getUser ()
Returns
Dynamics CRM connection's user
Definition at line 156 of file DynamicsCrm.php.
References $user.
{
         return $this->user;
     }
ParseDatas ($Datas, $Return) private
Parse the datas and update the object accordingly
Parameters
$xml SimpleXml to be parsed
Object CrmResponse
Returns
Object CrmResponse
Definition at line 1219 of file DynamicsCrm.php.
References ParseResultLine().
Referenced by GetCurrentUserInfo(), ParseRetrieve(), ParseRetrieveMultiple(), and Workflow().
{
         $NbResults = 0;
         $Results = array ();
         foreach ( $Datas as $Data ) {
             $ResultLine = $this->ParseResultLine ( $Data );
             $Results [$NbResults] = $ResultLine;
             $NbResults ++;
         }
         $Return->NbResult = $NbResults;
         $Return->Result = $Results;
         return $Return;
     }
ParseKeyPair ($data) private
Parameters
unknown $data
Returns
number|boolean|Ambigous <string, multitype:string , multitype:stdClass >|Ambigous <multitype:string , string, multitype:stdClass >
Definition at line 1265 of file DynamicsCrm.php.
References ParseResultLine().
Referenced by ParseResultLine().
{
         // liason simple
         if (isset ( $data->value->Value )) {
             $value = ( string ) $data->value->Value;
             // entit logique
         } else if (isset ( $data->value->LogicalName )) {
             $value = array (
                     'id' => ( string ) $data->value->Id,
                     'logicalname' => ( string ) $data->value->LogicalName,
                     'name' => ( string ) $data->value->Name
             );
         } else if (isset ( $data->value->Entities )) {
             $Entities = array ();
             foreach ( $data->value->Entities as $entity ) {
                 if (isset ( $entity->Entity->Attributes )) {
                     $Entities [] = $this->ParseResultLine ( $entity->Entity );
                 }
             }
             $value = $Entities;
         } else
             $value = ( string ) $data->value;
         if (! is_array ( $value )) {
             if (ctype_digit ( $value )) {
                 return ( int ) $value;
             } else if (is_float ( $value )) {
                 return ( float ) $value;
             } else if (is_bool ( $value )) {
                 return ( bool ) $value;
             } else
                 return $value;
         } else
             return $value;
     }
ParseResultLine ($Data) private
Parse the result of a ResultLine (will be used for both Retrieve and RetrieveMultiple)
Parameters
$Data SimpleXml Entity to be parsed
Returns
stdClass with correct Key/value for the resul line
Definition at line 1240 of file DynamicsCrm.php.
References ParseKeyPair().
Referenced by ParseDatas(), and ParseKeyPair().
{
         $ResultLine = new \stdClass ();
         if (isset ( $Data->Attributes )) {
             foreach ( $Data->Attributes as $keypair ) {
                 foreach ( $keypair->KeyValuePairOfstringanyType as $data ) {
                     $key = str_ireplace ( '.', '_', $data->key );
                     $ResultLine->$key = $this->ParseKeyPair ( $data );
                 }
             }
         } else {
             foreach ( $Data as $data ) {
                 if (isset ( $data->key )) {
                     $key = str_ireplace ( '.', '_', $data->key );
                     $ResultLine->$key = $this->ParseKeyPair ( $data );
                 }
             }
         }
         return $ResultLine;
     }
ParseRetrieve ($xml, $Return) private
Parse the result of a Retrieve Query
Parameters
$xml SimpleXml to be parsed
Object CrmResponse
Returns
Object CrmResponse
Definition at line 1310 of file DynamicsCrm.php.
References ParseDatas().
Referenced by call().
{
         $Datas = $xml->Body->RetrieveResponse->RetrieveResult;
         $Return = $this->ParseDatas ( $Datas, $Return );
         $Return->Result = $Return->Result [0];
         return $Return;
     }
ParseRetrieveMultiple ($xml, $Return) private
Parse the result of a RetrieveMultiple Query
Parameters
$xml SimpleXml to be parsed
Object CrmResponse
Returns
Object CrmResponse
Definition at line 1204 of file DynamicsCrm.php.
References ParseDatas().
Referenced by call().
{
         $Datas = $xml->Body->RetrieveMultipleResponse->RetrieveMultipleResult->Entities->Entity; // ->retrievemultipleresponse;//->retrievemultipleresult->entities->entity;
         $Return = $this->ParseDatas ( $Datas, $Return );
         return $Return;
     }
Retrieve ($Table, $Id, $Columns)
Retrieve ONE and ONLY ONE Line in CRM By ID
See also
DynamicsCrm::FormatFilter() For a better understanding of where clause
Parameters
string $Id mostly a GUID from the id column (key)
string $Table Table name
array $Columns list of columns to be shown , false to see all
array ('col1','col2',...)
Returns
Object CrmResponse
Bool $Error,
String $ErrorCode,
String $ErrorMessage,
$Result => false or std object with key parameter
Definition at line 207 of file DynamicsCrm.php.
References call(), and FormatColumn().
{
         // build Saop Enveloppe
         $SoapEnvelope = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://schemas.microsoft.com/xrm/2011/Contracts/Services" xmlns:con="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:arr="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
                          <soap:Body>
                             <ser:Retrieve>
                                     <ser:entityName>' . $Table . '</ser:entityName>
                                     <ser:id>' . $Id . '</ser:id>';
         $SoapEnvelope .= $this->FormatColumn ( $Columns );
         $SoapEnvelope .= '</ser:Retrieve>
                            </soap:Body>
                         </soap:Envelope>';
         // call
         Return $this->call ( "Retrieve", $SoapEnvelope );
     }
RetrieveMultiple ($Table, $Where, $Columns = false, $Join = false, $Order = false)
Retrieve Multiple Lines in CRM
See also
FormatFilter For a better understanding of where clause
Parameters
array $Where detail of $Where attribute
array $Columns detail of $Columns attribute
array $Order will change order of results
array(
1=>('Column'=> 'Colname','Order'=>'Asc'),
2=>('Column'=> 'Colname2','Order'=>'Desc'),
...);
Returns
object CrmResponse.
Bool $Error,
String $ErrorCode,
String $ErrorMessage,
$Result => false or array of std object with key parameter,
Definition at line 249 of file DynamicsCrm.php.
References $Aggregate, array_key_exists_r(), call(), FormatFetchAttribute(), FormatFetchEntity(), FormatFetchJoin(), FormatFetchOrder(), and GetErrorObject().
{
         // check if there is some agregate inside parameter
         if (is_array ( $Columns )) {
             if ($this->array_key_exists_r ( 'aggregate', $Columns ) || $this->array_key_exists_r ( 'groupby', $Columns )) {
                 $Aggregate = 'true';
             } else
                 $Aggregate = 'false';
         } else
             $Aggregate = 'false';
             // build Soap Enveloppe
         try {
                 $Entity = $this->FormatFetchEntity ( $Table );
                 $Attributes = $this->FormatFetchAttribute ( $Columns );
                 $Order = $this->FormatFetchOrder ( $Order );
                 $Filter = $this->formatFetchFilter ( $Where );
                 if ($Join !== false){
                     $Join = $this->FormatFetchJoin ( $Join );
                 }else $Join='';
             } catch ( Exception $e ) {
                 return $this->GetErrorObject ( $e->getMessage () );
             }
         $SoapEnvelope = '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
                              <s:Body>
                                 <RetrieveMultiple xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Services" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                                     <query i:type="a:FetchExpression" xmlns:a="http://schemas.microsoft.com/xrm/2011/Contracts">
                                          <a:Query>
                                                 &lt;fetch version=\'1.0\' output-format=\'xml-platform\' mapping=\'logical\' aggregate=\'' . $Aggregate . '\' distinct=\'false\'&gt;';
         $SoapEnvelope.=$Entity.$Attributes.$Order.$Filter.$Join;
         // add footer
         $SoapEnvelope .= '&lt;/entity&gt;
                                                &lt;/fetch&gt;
                 </a:Query>
                                     </query>
                                 </RetrieveMultiple>
                               </s:Body>
                         </s:Envelope>
                         ';
         // call
         Return $this->call ( "RetrieveMultiple", $SoapEnvelope );
     }
setPassword ($password)
Parameters
string $password Dynamics CRM connection's password
Definition at line 184 of file DynamicsCrm.php.
References $password.
Referenced by __construct().
{
         $this->password = $password;
         return $this;
     }
setServAdress ($serv_adress)
Parameters
string $serv_adress Dynamics CRM connection's Url to service
Definition at line 147 of file DynamicsCrm.php.
References $serv_adress.
Referenced by __construct().
{
         $this->serv_adress = $serv_adress;
         return $this;
     }
SetState ($Id, $Table, $StateCode, $StatusCode)
Parameters
unknown $Id
unknown $Table
unknown $StateCode
unknown $StatusCode
Returns
result|CrmResponse
Definition at line 437 of file DynamicsCrm.php.
References ExecuteBody(), and GetErrorObject().
{
         if (isset ( $this->StateCheck [$Table] [$StateCode] ) && in_array ( $StatusCode, $this->StateCheck [$Table] [$StateCode] )) {
             $Request = '<request i:type="b:SetStateRequest" xmlns:a="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:b="http://schemas.microsoft.com/crm/2011/Contracts">
        <a:Parameters xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
          <a:KeyValuePairOfstringanyType>
            <c:key>EntityMoniker</c:key>
            <c:value i:type="a:EntityReference">
              <a:Id>' . $Id . '</a:Id>
              <a:LogicalName>' . $Table . '</a:LogicalName>
              <a:Name i:nil="true" />
            </c:value>
          </a:KeyValuePairOfstringanyType>
        <a:KeyValuePairOfstringanyType>
            <c:key>State</c:key>
            <c:value i:type="a:OptionSetValue">
              <a:Value>' . $StateCode . '</a:Value>
            </c:value>
          </a:KeyValuePairOfstringanyType>
         <a:KeyValuePairOfstringanyType>
            <c:key>Status</c:key>
            <c:value i:type="a:OptionSetValue">
              <a:Value>' . $StatusCode . '</a:Value>
            </c:value>
          </a:KeyValuePairOfstringanyType></a:Parameters>
        <a:RequestId i:nil="true" />
        <a:RequestName>SetState</a:RequestName>
      </request>';
             return $this->ExecuteBody ( $Request );
         } else {
             $strPair = print_r ( $this->StateCheck [$Table], true );
             return $this->GetErrorObject ( 'Pair State and status not avaible for ' . $Table . ' should be in  State => array( avaible status) :  ' . $strPair );
         }
     }
setUser ($user)
Parameters
string $user Dynamics CRM connection's User
(LDAP) Domain/user
Definition at line 166 of file DynamicsCrm.php.
References $user.
Referenced by __construct().
{
         $this->user = $user;
         return $this;
     }
TestAgreggate ($Param) private
Parameters
unknown $Param
Exceptions
InvalidArgumentException
Definition at line 930 of file DynamicsCrm.php.
Referenced by FormatFetchAttribute().
{
         if (! in_array ( $Param, $this->Aggregate )) {
             $AggregateValue = print_r ( $this->Aggregate, true );
             throw new \InvalidArgumentException ( sprintf ( "Aggregate Invalid should be in : $AggregateValue" ) );
         }
     }
TestParameter ($Param, $field) private
Parameters
unknown $Param
unknown $field
Exceptions
InvalidArgumentException
Definition at line 919 of file DynamicsCrm.php.
Referenced by FormatAttribute(), FormatFetchAttribute(), and TestParameters().
{
         if (! isset ( $Param [$field] )) {
             $strArray = print_r ( $Param, true );
             throw new \InvalidArgumentException ( sprintf ( "Missing Parameter $field for array : $strArray" ) );
         }
     }
TestParameters ($Param, $Fields) private
Parameters
unknown $Param
unknown $Fields
Definition at line 908 of file DynamicsCrm.php.
References TestParameter().
Referenced by FormatAttribute(), FormatCondition(), FormatFetchJoin(), and FormatFetchOrder().
{
         foreach ( $Fields as $Field ) {
             $this->TestParameter ( $Param, $Field );
         }
     }
Update ($Table, $Params, $Id)
Update a row in CRM
Parameters
string $Table
the table name where you want to insert a row
Parameters
string $Id mostly a GUID from the id column (key) too see the dif operator
array $Params
'ColumnName' => Value
Returns
obj CrmResponse.
Bool $Error,
String $ErrorCode,
String $ErrorMessage,
$Result => true or false...
Definition at line 348 of file DynamicsCrm.php.
References call(), FormatAttributes(), and GetErrorObject().
{
         // check the array parameter first
         try {
             $Param = $this->FormatAttributes ( $Params );
         } catch ( Exception $e ) {
             return $this->GetErrorObject ( $e->getMessage () );
         }
         // build soap Enveloppe
         $SoapEnvelope = '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                             <soap:Body><Update xmlns="http://schemas.microsoft.com/xrm/2011/Contracts/Services">
             <entity xmlns:b="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
                     <b:Attributes xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
                        ' . $Param . '
                     </b:Attributes>
                     <b:EntityState i:nil="true"/>
                     <b:FormattedValues xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic"/>
                     <b:Id>' . $Id . '</b:Id>
                     <b:LogicalName>' . $Table . '</b:LogicalName>
                     <b:RelatedEntities xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic"/>
                 </entity></Update>
             </soap:Body>
         </soap:Envelope>';
         // call
         return $this->call ( 'Update', $SoapEnvelope );
     }
Workflow ($EntityId, $WorkflowId)
Parameters
unknown $EntityId
unknown $WorkflowId
Returns
result
Definition at line 501 of file DynamicsCrm.php.
References ExecuteBody(), and ParseDatas().
{
         $Request = '<request i:type="b:ExecuteWorkflowRequest" xmlns:a="http://schemas.microsoft.com/xrm/2011/Contracts" xmlns:b="http://schemas.microsoft.com/crm/2011/Contracts">
                     <a:Parameters xmlns:c="http://schemas.datacontract.org/2004/07/System.Collections.Generic">
                     <a:KeyValuePairOfstringanyType>
                     <c:key>EntityId</c:key>
     <c:value i:type="d:guid" xmlns:d="http://schemas.microsoft.com/2003/10/Serialization/">$EntityId</c:value>
     </a:KeyValuePairOfstringanyType>
     <a:KeyValuePairOfstringanyType>
     <c:key>WorkflowId</c:key>
     <c:value i:type="d:guid" xmlns:d="http://schemas.microsoft.com/2003/10/Serialization/">$WorkflowId</c:value>
     </a:KeyValuePairOfstringanyType>
     </a:Parameters>
     <a:RequestId i:nil="true" />
     <a:RequestName>ExecuteWorkflow</a:RequestName>
     </request>';
         $Return = $this->ExecuteBody ( $Request );
         $Return = $this->ParseDatas ( $Return->Result->Body->ExecuteResponse->ExecuteResult->Results, $Return );
         return $this->ExecuteBody ( $Request );
     }
Field Documentation
$Aggregate = array ('avg','max','min','sum','count','countcolumn','countdistinct') private
Definition at line 103 of file DynamicsCrm.php.
Referenced by RetrieveMultiple().
$Operator private
Initial value:
= array(
            '0'=>array('eq-userid','ne-userid','eq-bysinessid','ne-bysinessid',
                    'eq-userteams','last-seven-days','last-fiscal-period','last-fiscal-year','last-month',
                    'last-week','last-year','next-seven-days','next-fiscal-period','next-fiscal-year','next-month','next-week',
                    'next-year','null','this-fiscal-period','this-fiscal-year','this-month','this-week','this-year','today','not-null','tomorrow','yesterday') ,
            '1'=>array('like','not-like','eq','ge','gt','le','lt','ne','on','on-or-after','on-or-before',
                    'in-fiscal-period','in-fiscal-year','last-x-days','last-x-fiscal-periods','last-x-fiscal-years','last-x-hours',
                    'last-x-months','last-x-weeks','last-x-years','next-x-days','next-x-fiscal-periods','next-x-fiscal-years',
                    'next-x-hours','next-x-months','next-x-weeks','next-x-years','olderthan-x-months') ,
            '2'=> array('not-in','in'),
            '3'=> array('between','not-between','in-fiscal-period-and-year','in-or-after-fiscal-period-and-year','in-or-before-fiscal-period-and-year')
    )
Definition at line 104 of file DynamicsCrm.php.
$password
Definition at line 71 of file DynamicsCrm.php.
Referenced by getPassword(), and setPassword().
$serv_adress
Definition at line 69 of file DynamicsCrm.php.
Referenced by getServAdress(), and setServAdress().
$StateCheck private
Definition at line 72 of file DynamicsCrm.php.
$user
Definition at line 70 of file DynamicsCrm.php.
Referenced by getUser(), and setUser().
The documentation for this class was generated from the following file:
lib/DynamicsCrm.php